name: CI - Test & Docker Build

on:
  push:
    branches:
      - main
  pull_request:

permissions: 
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ§¾ Checkout repository
      uses: actions/checkout@v3

    - name: ðŸ Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: ðŸ“¦ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ðŸ” Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ðŸ—ï¸ Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/chrisshikayri/chururu:latest
  
    - name: ver las variables de seguridad
      run: |
        echo "probando conexion ssh con:"
        echo "Host: ${{secrets.VPS_HOST }}"
        echo "usuario: ${{secrets.VPS_USER}}"
        echo "puerto: ${{secrets.VPS_SSH_PORT }}"
        echo "contraseÃ±a: ${{secrets.VPS_PASSWORD}}"

    - name: probar conexion ssh
      uses: appleboy/ssh-action@v1
      with:
       host: ${{secrets.VPS_HOST}}
       username: ${{secrets.VPS_USER}}
       password: ${{secrets.VPS_PASSWORD}}
       port: ${{secrets.VPS_SSH_PORT}}
       script: |
        echo "contraseÃ±as y datos de github"
        hostname
        whoami
        uptime

    - name: pasar el stack.yml al servidor
      uses: appleboy/scp-action@v1
      with:
       host: ${{secrets.VPS_HOST}}
       username: ${{secrets.VPS_USER}}
       password: ${{secrets.VPS_PASSWORD}}
       port: ${{secrets.VPS_SSH_PORT}}
       source: "stack.yml"
       target: "/home/${{secrets.VPS_USER}}/despliegue"

    - name: despliege de servisios
      uses: appleboy/ssh-action@v1
      with:
       host: ${{secrets.VPS_HOST}}
       username: ${{secrets.VPS_USER}}
       password: ${{secrets.VPS_PASSWORD}}
       port: ${{secrets.VPS_SSH_PORT}}
       script: |
        echo "servicios desplegados"
        
        docker stack rm chris || true

        echo "==> Descargando la imagen del github"  
         # docker pull ghcr.io/chrisshikayri/chururu:latest

        echo "==> Desplegando stack..."
            docker stack deploy -c stack.yml --with-registry-auth chris